version: '2'
services:
    postgressvc-app:
        image: postgressvc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgressvc-postgresql:5432/postgressvc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    postgressvc-postgresql:
        extends:
            file: postgresql.yml
            service: postgressvc-postgresql
