version: '2'
services:
    postgressvc-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/postgressvc/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgressvc
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
