apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgressvc
  annotations:
     "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgressvc
  template:
    metadata:
      labels:
        app: postgressvc
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/path: "/postgressvc/metrics"
         prometheus.io/port: "8080"
         prometheus.io/scrape: "true"
    spec:
      containers:
      - name: postgressvc
        image: postgressvc:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
        - containerPort: 8090
        - containerPort: 8080
        env: 
        - name: JAEGER_SERVICE_NAME
          value: postgressvc
        - name: JAEGER_ENDPOINT
          value: 'http://jaeger-collector.observability.svc:14268/api/traces'
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: '1'
        - name: JAEGER_REPORTER_LOG_SPANS
          value: 'true'
        - name: JAEGER_TAGS
          value: 'version=${VERSION}'